const fs = require("fs");
const path = require("path");
const { Client } = require("pg");

function normalizeSqlForPostgres(sql) {
  let s = String(sql || "").trim();

  s = s.replace(/datetime\(\s*['"]now['"]\s*\)/gi, "CURRENT_TIMESTAMP");
  s = s.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, "INSERT INTO");
  s = s.replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY");
  s = s.replace(
    /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi,
    "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  );

  let paramIndex = 0;
  s = s.replace(/\?/g, () => `$${++paramIndex}`);

  if (
    /\bINSERT\s+INTO\b/i.test(s) &&
    /\bVALUES\b/i.test(s) &&
    !/\bON\s+CONFLICT\b/i.test(s)
  ) {
    s = s.replace(/(\s*;?\s*)$/, " ON CONFLICT DO NOTHING$1");
  }

  return s;
}

(async () => {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });

  await client.connect();

  const schema = fs.readFileSync(
    path.join(process.cwd(), "database", "schema.sql"),
    "utf8",
  );

  for (const statement of schema
    .split(/;\s*\n+/)
    .map((s) => s.trim())
    .filter(Boolean)) {
    await client.query(normalizeSqlForPostgres(statement));
  }

  console.log("schema ready");

  await client.query("DELETE FROM auth_sessions");
  await client.query("DELETE FROM password_reset_tokens");
  await client.query("DELETE FROM transactions");
  await client.query("DELETE FROM booth_services");
  await client.query("DELETE FROM services");
  await client.query("DELETE FROM booths");
  await client.query("DELETE FROM users");

  console.log("reset complete");
  await client.end();
  process.exit(0);
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
